set -g prefix M-b

set -g default-terminal "xterm-256color"

unbind r
bind r \
        source-file ~/.config/tmux/tmux.conf \;\
        display 'Reloaded tmux config'

unbind Left
unbind Right
unbind Up
unbind Down

bind -r Left resize-pane -L
bind -r Right resize-pane -R
bind -r Up resize-pane -U
bind -r Down resize-pane -D

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @select_color "#f5c2e7"

set -g status-bg default
set -g status-fg "#11111b"

set-option -g status-style bg=default

set-option -g status-left "\
#[bg=#cba6f7] 󰖲 #S \
#[fg=#cba6f7, bg=default] \
"

set -g status-right "\
#[fg=#{@select_color}] \
#[fg=#11111b, bg=#{@select_color}] %a %d %b \
#[fg=#cba6f7]\
#[fg=#11111b, bg=#cba6f7]  %H:%M \
"

set-window-option -g window-status-current-format "\
#[fg=#{@select_color}]\
#[fg=#11111b, bg=#{@select_color}] #I* |\
#[fg=#11111b, bold] #W \
#[fg=#{@select_color}, bg=default]\
"

set-window-option -g window-status-format "\
#[fg=#cba6f7]\
#[fg=#11111b, bg=#cba6f7] #I | #W \
#[fg=#cba6f7, bg=default]\
"


